### ISSUE TITLE
Can't figure out how to run it

### ISSUE THREAD

**Issue by Do-odle** [homielab/audiobookapp#15]
Hello, I just installed Android Studio. I need to create an Audio Book app for a school project. I am a complete newbie. Can you please explain to me how can I run your project? Also can't seem to find how the additional configuration works. I created one that shows when I open a new project, but with this one can't seem to find it. Also, search a whole lot on the web. Everyone said that you should Sync Project with Project Files but that doesn't show at the File tab. Even the create new module tab doesn't appear. I am lost :(

**Comment by minhtc** [comment]
@Do-odle This project is based on react-native, you should start with react-native document to know how to run a project: https://reactnative.dev/docs/getting-started

**Comment by Do-odle** [comment]
Hello again, I read your reply and tried again. This time after some YouTube tutorials I understood what React is. I also used the commands at the terminal to run the app. I did the cloning (first command) then when I try to execute the npm install, it says the npm term is not recognized. I installed Node.js and installed some npm extensions, still can't figure out how to fix it. Can you please help me a bit?

**Comment by minhtc** [comment]
> Hello again, I read your reply and tried again. This time after some YouTube tutorials I understood what React is. I also used the commands at the terminal to run the app. I installed Visual Studio Code and opened the project there. I did the cloning (first command) then when I try to execute the npm install, it says the npm term is not recognized. I installed Node.js and installed some npm extensions, still can't figure out how to fix it. Can you please help me a bit?

Just updated audiobookapp project to the latest react-native version. Please try to setup and run again.
