### ISSUE TITLE
"react-recontext" library error while installing node modules 

### ISSUE THREAD

**Issue by arbabahmed1997** [homielab/audiobookapp#18]
<img width="1440" alt="Screenshot 2022-01-30 at 6 09 57 PM" src="https://user-images.githubusercontent.com/73573215/151701191-e5819731-a753-4bae-af59-610ec7709d60.png">
Any solution ?

**Comment by minhtc** [comment]
> <img alt="Screenshot 2022-01-30 at 6 09 57 PM" width="1440" src="https://user-images.githubusercontent.com/73573215/151701191-e5819731-a753-4bae-af59-610ec7709d60.png">
> 
> Any solution ?

Please uninstall package @homielab/react-recontext by run this command:
```
npm uninstall @homielab/react-recontext
```

**Comment by arbabahmed1997** [comment]
<img width="1440" alt="Screenshot 2022-01-31 at 3 44 21 PM" src="https://user-images.githubusercontent.com/73573215/151780074-a3063662-4f6a-4ae8-8f97-2754b06bb928.png">
Now, this happens. Any solution?

**Comment by minhtc** [comment]
> <img alt="Screenshot 2022-01-31 at 3 44 21 PM" width="1440" src="https://user-images.githubusercontent.com/73573215/151780074-a3063662-4f6a-4ae8-8f97-2754b06bb928.png">
> 
> Now, this happens. Any solution?

I've pushed a commit to fix the issue. Please clear all your changes, pull the latest codes and try again.

**Comment by arbabahmed1997** [comment]
Yes it has been fixed, thank you !
