### ISSUE TITLE
Error Installing React-recontext

### ISSUE THREAD

**Issue by RFMVasconcelos** [homielab/audiobookapp#20]
Hi @homielab,

Thank you for building this 💯  This project is super cool! 

I have been quite into Audiobooks lately and am pushing to bring them to Portugal - https://radiobooks.pt - basing my app development on your work will accelerate greatly time to get this in the hands of users. 

I am testing out, but can't seem to be able to install the react-recontext dependency.. Any thoughts?

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/27001378/154121168-0896fe44-6cdb-4c50-a6d5-5ef3dafd96fb.png">

Many thanks!

**Comment by minhtc** [comment]
Try to uninstall the old packages:
npm uninstall react-recontext
npm uninstall @homielab/react-recontext
nom install —save react-recontext@lastest
