### ISSUE TITLE
Can not run into Android

### ISSUE THREAD

**Issue by poojan010** [homielab/audiobookapp#31]
You have to update the react native version to be able to run the app in the android 

Issue Link : https://github.com/facebook/react-native/issues/35210

@minhtc 
If you want i can generate PR for this issue and Iphone 14 pro header issue

**Comment by minhtc** [comment]
> You have to update the react native version to be able to run the app in the android
> 
> Issue Link : [facebook/react-native#35210](https://github.com/facebook/react-native/issues/35210)
> 
> @minhtc If you want i can generate PR for this issue and Iphone 14 pro header issue

Yes, PR welcome
Thank you so much 🤗🤗🤗

**Comment by poojan010** [comment]
Okay @minhtc 
I'll generate PR today or max tomorrow
